services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: legaldocs-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE=http://localhost:8000
    container_name: legaldocs-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped
